# Generated by Django 3.0.4 on 2020-07-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200703_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
